/*
 ********************************************************************
 * Licensed Materials - Property of HCL                             *
 *                                                                  *
 * Copyright HCL Technologies Ltd. 2022. All Rights Reserved.       *
 *                                                                  *
 * Note to US Government Users Restricted Rights:                   *
 *                                                                  *
 * Use, duplication or disclosure restricted by GSA ADP Schedule    *
 ********************************************************************
 */

// Use our DX shared library
@Library("dx-shared-library") _

pipeline {
    agent {
        label 'build_docu'
    }

    stages {
        stage("Publish doc") {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: "jenkins-git", keyFileVariable: 'SSH_KEY')]) {
                    sh """
                        docker run -d --name doc-builder quintana-docker.artifactory.cwp.pnp-hcl.com/dxubi:v1.0.0_8.5-204 /bin/bash -c "mkdir /build && mkdir /root/.ssh && tail -f /dev/null"
                        docker cp ${SSH_KEY} doc-builder:/root/.ssh/id_rsa
                        docker cp ${WORKSPACE}/jenkins/helpers/* /build
                        docker exec /bin/bash /build/01-publish-doc.sh
                    """
                }
            }
        }
    }

    post {
        cleanup {
            sh """
                docker stop doc-builder || true
                docker rm doc-builder || true
            """
            dxWorkspaceDirectoriesCleanup()
        }
    }
}